{{ if .Values.defaultLandingPage }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-custom-page
  labels:
    app: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx</title>
    </head>
    <body>
        <h1>Hello from ConfigMap!</h1>
        <p>This page is served from a ConfigMap.</p>
    </body>
    </html>
{{ end }}